config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :exercises
  resources :workouts
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root 'workouts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
# frozen_string_literal: true

class Exercise < ApplicationRecord
  validates :description, :name, presence: true
  validates :intensity, presence: true, inclusion: { in: 0..10 }, numericality: { only_integer: true }

  has_many :exercise_workouts
  has_many :workouts, through: :exercise_workouts
end

app/models/exercise_workout.rb
# frozen_string_literal: true

class ExerciseWorkout < ApplicationRecord
  belongs_to :exercise
  belongs_to :workout
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/models/workout.rb
# frozen_string_literal: true

class Workout < ApplicationRecord
  validates :name, presence: true

  has_many :exercise_workouts, dependent: :delete_all
  has_many :exercises, through: :exercise_workouts
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/confirmations_controller.rb
# frozen_string_literal: true

class ConfirmationsController < Devise::ConfirmationsController
  private

  def after_confirmation_path_for(_resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    workouts_path
  end
end

app/controllers/exercises_controller.rb
# frozen_string_literal: true

class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[show edit update destroy]

  def index
    @exercises = Exercise.all
  end

  def show; end

  def new
    @exercise = Exercise.new
  end

  def edit; end

  def create
    @exercise = Exercise.new(exercise_params)

    if @exercise.save
      redirect_to @exercise, notice: 'Exercise was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @exercise.update(exercise_params)
      redirect_to @exercise, notice: 'Exercise was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @exercise.destroy
    redirect_to exercises_url, notice: 'Exercise was successfully destroyed.'
  end

  private

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:name, :description, :intensity)
  end
end

app/controllers/workouts_controller.rb
# frozen_string_literal: true

class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    @workouts = Workout.all
  end

  def show; end

  def new
    @workout = Workout.new
  end

  def edit; end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      redirect_to @workout, notice: 'Workout was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout, notice: 'Workout was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @workout.destroy
    redirect_to workouts_url, notice: 'Workout was successfully destroyed.'
  end

  private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:name, exercise_ids: [])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/exercises/_form.html.erb
<%= form_with(model: exercise) do |form| %>
  <% if exercise.errors.any? %>
    <div id='error_explanation' class='alert alert-danger' role='alert'>
      <h5><%= pluralize(exercise.errors.count, 'error') %> prohibited this exercise from being saved:</h5>
      <ul>
        <% exercise.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='mb-3'>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %> 
  </div>
  <div class='mb-3'>
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control'%>
  </div>
  <div class='mb-3'>
    <%= form.label :intensity %>
    <%= form.text_area :intensity, class: 'form-control', placeholder: 'Must be a number between 0 and 10' %>
  </div>
  <div class='actions'>
    <%= form.submit class: 'btn btn-success min-width-btn' %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form', exercise: @exercise %>

<br>

<div class='.d-inline-flex'>
  <%= link_to 'Show this exercise', @exercise,  class:'btn btn-primary' %> 
  <%= link_to 'Back to exercises', exercises_path, class:'btn btn-secondary' %>
</div>

app/views/exercises/index.html.erb
<h1>Exercises</h1>

<div id='exercises'>
  <table class='table table-bordered'>
    <thead class='table-light'>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @exercises.each do |exercise| %>
        <tr>
          <td><%= exercise.name %></td>
          <td><%= link_to 'Show this exercise', exercise, class:'btn btn-info' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New exercise', new_exercise_path, class:'btn btn-primary' %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form', exercise: @exercise %>

<div class='mb-3'><%= link_to 'Back to exercises', exercises_path, class: 'btn btn-secondary' %></div>

app/views/exercises/show.html.erb
<div id='exercise'>
<h2>Exercise: <%= @exercise.name%></h2>
  <table class='table table-bordered align-middle'>
    <thead class='table-light'>
      <tr>
        <th><strong>Description</strong></th>
        <th><strong>Intensity</strong></th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @exercise.description %></td>
          <td><%= @exercise.intensity %></td>
          <td><%= link_to 'Edit this exercise', edit_exercise_path(@exercise), class: 'btn btn-primary' %> <%= button_to 'Destroy this exercise', @exercise, method: :delete, class: 'btn btn-danger' %></td>
        </tr>
    </tbody>
  </table>
</div>

<div class='d-inline-flex'>
  <%= link_to 'Back to exercises', exercises_path, class:'btn btn-secondary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutApp</title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3' crossorigin='anonymous'>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class='d-flex justify-content-between'>
        <div class='d-flex justify-content-end'>
          <%= link_to 'Create an Exercise', new_exercise_path	 %> |
          <%= link_to 'Create a Workout', new_workout_path %> |
          <%= link_to 'Show Exercises', exercises_path%> |
          <%= link_to 'Show Workout', workouts_path%> 
        </div>
        <div class='d-flex justify-content-end'>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
        </div>
      </div>
    <% else %>
      <%= button_to 'Sign in',  new_user_session_path, method: :get %>
    <% end %>
    <%= yield %>
    <p style ='color: green'class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
  </body>
</html>

app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |form| %>
  <% if workout.errors.any? %>
    <div id='error_explanation' class='alert alert-danger' role='alert'>
      <h5><%= pluralize(workout.errors.count, 'error') %> prohibited this exercise from being saved:</h5>
      <ul>
        <% workout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='mb-3'>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %> 
  </div>

  <%= form.label :Add_Exercises %>
  <div class='mb-3'>
    <%= form.collection_check_boxes :exercise_ids, Exercise.all, :id, :name %>
  </div>
  <div class='actions'>
    <%= form.submit class: 'btn btn-success min-width-btn' %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form', workout: @workout %>

<br>

<div class='.d-inline-flex'>
  <%= link_to 'Show this exercise', @workout,  class:'btn btn-primary' %> 
  <%= link_to 'Back to exercises', workouts_path, class:'btn btn-secondary' %>
</div>

app/views/workouts/index.html.erb
<h1>Workouts</h1>

<div id='workouts'>
  <table class='table table-bordered'>
    <thead class='table-light'>
      <tr>
        <th>Name</th>
        <th>Exercises</th>
      </tr>
    </thead>
    <tbody>
      <% @workouts.each do |workout| %>
        <tr>
          <td><%= workout.name %></td>
          <td><%= workout.exercises.count %></td>
          <td><%= link_to 'Show this workout', workout, class:'btn btn-info' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'New workout', new_workout_path, class:'btn btn-primary' %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form', workout: @workout %>

<div class='mb-3'><%= link_to 'Back to workouts', workouts_path, class: 'btn btn-secondary' %></div>

app/views/workouts/show.html.erb
<div id='workout'>
  <h2>Workout details:</h2>
  <h3><%= @workout.name %> </h3>
  <table class='table table-bordered align-middle'>
    <thead class='table-light'>
      <tr>
        <th><strong>Exercise name</strong></th>
        <th><strong>Description</strong></th>
        <th><strong>intensity</strong></th>
      </tr>
    </thead>
    <tbody>
        <% @workout.exercises.each do |exercise| %>
          <tr>
            <td><%= exercise.name %></td>
            <td><%= exercise.description %></td>
            <td><%= exercise.intensity %></td>
          </tr>
        <% end %>
    </tbody>
 </table>
</div>

<div class='d-inline-flex'>
  <%= link_to 'Edit this workout', edit_workout_path(@workout), class: 'btn btn-primary' %>
  <%= button_to 'Destroy this workout', @workout, method: :delete, class: 'btn btn-danger' %>
  <%= link_to 'Back to workouts', workouts_path, class: 'btn btn-secondary' %>
</div>